### ISSUE TITLE
winapps installer wont run 

### ISSUE THREAD

**Issue by JOEYOCHO** [winapps-org/winapps#115]
when trying to run installer.sh i get this output

Installing...
  Checking for installed apps in RDP machine (this may take a while)... Finished.

The RDP connection failed to connect or run. Please confirm FreeRDP can connect with:
  bin/winapps check

If it cannot connect, this is most likely due to:
  - You need to accept the security cert the first time you connect (with 'check')
  - Not enabling RDP in the Windows VM
  - Not being able to connect to the IP of the VM
  - Incorrect user credentials in winapps.conf
  - Not merging install/RDPApps.reg into the VM

this happens even though i have setup rdp properly and bin/winapps check runs fine. I also see a cmd window popup for a tiny bit then close

EDIT: old repo of winapps works

**Comment by graven04** [comment]
I am getting this same error. My VM was working perfectly before and suddenly it stopped working. I reinstalled the whole thing again and followed every part of the guide (KVM). However, when i try to run the installer.sh it still get the same output as @JOEYOCHO. 

However, now instead of the cmd i get this instead:
![image](https://github.com/winapps-org/winapps/assets/93924539/57d26896-b53e-4fe7-a6cc-b2c28765a011)

**Comment by JOEYOCHO** [comment]
i also get this if i use xfreerdp but xfreerdp3 works fine and gets the issue i listed above @graven04

**Comment by oskardotglobal** [comment]
@graven04 Install freerdp3. Also, the installation with KVM is unsupported.

**Comment by oskardotglobal** [comment]
@JOEYOCHO Wayland is unsupported at the moment. See #19.

**Comment by graven04** [comment]
It works now in wayland with the KVM method using the new merged repo
