### ISSUE TITLE
How to reach the Docker VM from "outside"?

### ISSUE THREAD

**Issue by eylenburg** [winapps-org/winapps#118]
This is probably not an actual bug but my personal question and is not covered by the documentation.

I installed Docker with the Windows VM in a Distrobox container (podman container) as I am using an immutable distro (Fedora Kinoite). Now, inside the Distrobox container I can connect to to the Windows VM using the IP 127.0.0.1 as described in your guide. However, this doesn't work from outside the distrobox container. So for example using freerdp from my host won't work.

`docker inspect windows` says the IP is 172.18.0.2 and the Windows VM itself reports its IP as 20.20.20.21. None of these (nor 127.0.0.1) work to connect with Remmina or FreeRDP from the host though.

**Comment by LDprg** [comment]
You installed podman within a distrobox? Thats basically podman in podman. You really need be careful with this setup since you might have no access to the ip dependent where the command runs (Nat, firewalls, etc). You could try to add portforwarding to the distrobox container. You should also check if the distrobox is running.

Maybe you should just run the setup without cascading podman?

**Comment by eylenburg** [comment]
Yeah, probably best to avoid nesting containers like this. I thought it would be a clean solution for immutable systems but probably out of scope.
