### ISSUE TITLE
Limitations of RDP_SCALE Settings and Request for Higher Values

### ISSUE THREAD

**Issue by iamcheyan** [winapps-org/winapps#18]
Great program, thank you for your work.
May I ask if RDP_SCALE can only be set to 100|140|160|180? Can it be set to a higher value, such as 300, 400, or 500?

**Comment by oskardotglobal** [comment]
RDP_SCALE is a value passed directly to the `xfreerdp` command, so you should refer to its documentation instead.

**Comment by LDprg** [comment]
The RDP protocol doesn't allow all sizes for scaling on the host (ask microsoft why). But freerdp supports /smart-sizing:1280x768 which just does some client side scaling. Just for reference, [here](https://github.com/FreeRDP/FreeRDP/issues/5253) someone ask a similar question for freerdp.

**Comment by oskardotglobal** [comment]
This question seems answered, closing.

**Comment by wolfallein** [comment]
I had the same problem and the combination of `smart-sizing` and `size`  only applies an upscaling with quality loss.

The option that best worked for me was `scale-desktop`.
 For me it looks a better alternative than `scale`.

The `scale-desktop` works with: 100, 125, 150, 175, 200, 250, 300, 400, 500
I didn't notice quality loss when using `scale-desktop` instead of `scale`.

I guess it would be beneficial to replace `scale` with `scale-desktop` for the winapps scripts?
