### ISSUE TITLE
Program windows not responding after changing size

### ISSUE THREAD

**Issue by acaxxx** [winapps-org/winapps#55]
Hi
When I run REAPER or notepad.exe using winapps and click on the unmaximize button the window stops responding to mouse input. I have to ALT-F4 from it. Is there any workaround for this issue? I'm using Cinnamon/Mutter on Arch Linux

**Comment by LDprg** [comment]
Wayland is currently not supported. Your issue seems like a xfreerdp bug when running in xwayland. However this cannot be fixed until the release of sdl-freerdp (which wouldn't be ready until sdl 3.0), since there is currently other way.

Currently winapps only supports X11 until the release of sdl-freerdp. So you can try running winapps with X11, if the problem still exist feel free to reopen this issue.
